### ISSUE TITLE
Add Cleakka as a new cache/session store

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum#125]
Cleakka, which is based on Akka, is intended as an alternative to Hazelcast.

TODO:
- Add -XX:MaxDirectMemorySize to runner.sh and Xitrum Guide
- Use it (default to 64 MB) to limit server side session store and cache

**Comment by l15k4** [comment]
Hey, Cleakka won't be part of xitrum I guess, are you still planning to do so? Or push Cleakka forward? There still doesn't seem to be an alternative to Cleakka. I've found myself at need of something like this many times, I'm always working that around.

**Comment by ngocdaothanh** [comment]
Cleakka is not ready yet. I have no plan to move it forward.
If you want to maintain and move if forward, I can transfer the ownership of that project to you.

You can use [xitrum-hazelcast](https://github.com/xitrum-framework/xitrum-hazelcast).
