### ISSUE TITLE
Add form binding

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum#457]
https://www.playframework.com/documentation/2.4.x/ScalaForms

**Comment by ngocdaothanh** [comment]
Rich client is popular now.
Xitrum should focus more on server side and less on traditional client side interaction like this.

**Comment by tolyo** [comment]
While I completely agree, I think Xitrum can really benefit from a client-side package manager to complement the server (at the very least to package SockJS). Phoenix has adopted the most practical approach to this with their [default inclusion](http://www.phoenixframework.org/docs/static-assets) of Brunch. Please consider this [quick sample ](https://github.com/tolyo/reactive-xitrum) following the same route.

**Comment by ngocdaothanh** [comment]
👍
