### ISSUE TITLE
Make respondSockJsXxx return Future like other respondXxx methods

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum#503]

**Comment by georgeOsdDev** [comment]
I tried to integrate this issue like below

SockJsAction.scala
```scala
  def respondSockJsText(text: String): ChannelFuture = {
    val f = sessionActorRef ? MessageFromHandler(text)
    Await.result(f, timeout).asInstanceOf[ChannelFuture]
  }
```

In sockjs/SockJSActions.scala sockjs/NonWebSocketSession.scala
```scala
      case MessageFromHandler(text) =>
        sender ! respondWebSocketText(text)
```

But in some case with NonWebSocketSession, SockJSActor can not return ChannelFuture to sender (SockJsAction).

https://github.com/xitrum-framework/xitrum/blob/master/src/main/scala/xitrum/sockjs/NonWebSocketSession.scala#L151-160

**Comment by ngocdaothanh** [comment]
About the result: I've changed the result to [Future](http://netty.io/4.0/api/io/netty/util/concurrent/Future.html), not [ChannelFuture](http://netty.io/4.0/api/io/netty/channel/ChannelFuture.html), because the real channel socket can be on another machine.

About the implementation: Should not use `Await`. Instead, to implement, you can use [DefaultPromise](http://netty.io/4.0/api/io/netty/util/concurrent/DefaultPromise.html):
* Create a `DefaultPromise`, remember it, and return it.
* When there's result, call `setSuccess` or `setFailure` (`sessionActorRef` dies etc.).
