### ISSUE TITLE
Add config maxHeaderSize (for the entire HTTP header, defaults to 8192)

### ISSUE THREAD

**Issue by caiiiycuk** [xitrum-framework/xitrum#512]
Hi again! 

Search engines (like google or yandex) adds a `Referer` header to request. Sometimes (in our case) this header can exceed the maximum HTTP header length and in this case server drops the connection. We need way to configure this option (to increase maximum header length).

It will be good if we can configure this options in xitrum.conf, like in play framework:
https://www.playframework.com/documentation/2.3.x/ProductionConfiguration

**Comment by caiiiycuk** [comment]
UPD: In the link below please goes to "Advanced HTTP server configuration" section.

**Comment by ngocdaothanh** [comment]
@georgeOsdDev Can you take care of this issue?

You need to modify this line:
https://github.com/xitrum-framework/xitrum/blob/1ae8e07f4476763bc2361f62d61d4d086e4ce368/src/main/scala/xitrum/handler/DefaultHttpChannelInitializer.scala#L117

HttpRequestDecoder:
http://netty.io/4.0/api/io/netty/handler/codec/http/HttpRequestDecoder.html

**Comment by georgeOsdDev** [comment]
The maximum length of all headers. If the sum of the length of each header exceeds this value, a TooLongFrameException will be raised.

When TooLongFrameException(DecoderException) was thrown, it will be caught at BadClientSilencer.
Should we respond 400?

**Comment by ngocdaothanh** [comment]
Because this exception is thrown from a handler to other handlers in the pipeline, I think it's the only good place where we can catch the exception. I guess there's no better place.

**Comment by ngocdaothanh** [comment]
The problem described at https://groups.google.com/forum/#!topic/xitrum-framework/TYm1D0GoE-Q may be related to https://github.com/netty/netty/pull/3460
