### ISSUE TITLE
Update sockjs-client from 0.3.4-1 to 1.0.0

### ISSUE THREAD

**Issue by georgeOsdDev** [xitrum-framework/xitrum#533]
https://github.com/sockjs/sockjs-client/releases
https://github.com/webjars/sockjs-client/releases/tag/sockjs-client-1.0.0

**Comment by ngocdaothanh** [comment]
@georgeOsdDev You forgot to update the version number in the source code. I've fixed it via https://github.com/xitrum-framework/xitrum/commit/02ced966f24c0875949dcda537df358898a8ab3e

I'll release Xitrum 3.24.0 in a few hours.

**Comment by georgeOsdDev** [comment]
:dizzy_face: sorry
