### ISSUE TITLE
params extraction also works for request with content type application/json

### ISSUE THREAD

**Issue by caiiiycuk** [xitrum-framework/xitrum#550]
Request example
```
//Request Headers
Content-Type:application/json;charset=UTF-8

//Request Payload
{key: [1, 2, 3], locale: "ru-RU", optional: "value"}
```

Extraction code:
```scala
//in controller
val keys = params[Int]("key") // List[Int]
val locale = param[String]("locale") // String
val optional = paramo[String]("optional") // Option[String]
```

**Comment by ngocdaothanh** [comment]
This feature looks nice :+1:

**Comment by caiiiycuk** [comment]
https://github.com/xitrum-framework/xitrum/pull/551

**Comment by ngocdaothanh** [comment]
Thanks. I've commented about just coding style. I'll comment more later if I find there's any logic that can be improved.

**Comment by ngocdaothanh** [comment]
Thanks :+1:
I've merged your PR.
I'll tune a little more.

I want to wait for JSON4S 3.3 to be released before releasing a new version of Xitrum:
https://github.com/json4s/json4s/pull/263

**Comment by ngocdaothanh** [comment]
@caiiiycuk 
JSON4S 3.3 has not been released yet, so I think we should release a new version of Xitrum soon without it.
