### ISSUE TITLE
Update Swagger from 1.2 to 2.0

### ISSUE THREAD

**Issue by ngocdaothanh** [xitrum-framework/xitrum#558]
Specs:
* 1.2: https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md
* 2.0: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
* 1.2 to 2.0 migration guide: https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide

Swagger-UI is updated from 2.0.24 (for Swagger spec 1.2) to 2.1.1 (for Swagger spec 2.0) at #559.

**Comment by ngocdaothanh** [comment]
@caiiiycuk 

Hi Aleksander, 
You added Swagger 1.2 to Xitrum.
Can you also take care of this issue?
Thanks.

**Comment by ngocdaothanh** [comment]
@caiiiycuk I'm taking care of this issue. It seems that the current Swagger in Xitrum is even older than 1.2, back to the time when Swagger was not versioned!

**Comment by caiiiycuk** [comment]
@ngocdaothanh 
Sorry, I didn't saw notification about this issue. I can try to fix this issue.

**Comment by ngocdaothanh** [comment]
@caiiiycuk I'm doing this issue. I think I can finish it in a few hours.

**Comment by ngocdaothanh** [comment]
I've updated Xitrum Guide:
https://github.com/xitrum-framework/xitrum-doc/commit/3672dbd29b23c0897ce6b670c03873c3e2aac7ff

I'll mention changes in the Xitrum 3.25.0 announcement.
