### ISSUE TITLE
Support for ServerSentEvents?

### ISSUE THREAD

**Issue by suyambuganesh** [xitrum-framework/xitrum#569]
Does xitrium implements Server Sent Events? 
http://www.w3.org/TR/eventsource/

**Comment by caiiiycuk** [comment]
Yes it is. See, http://xitrum-framework.github.io/guide/3.25/singlehtml/en/index.html#event-source. We use xitrum for send events from server in one of our projects.

**Comment by suyambuganesh** [comment]
Thanks for the link. I missed it somehow.
