### ISSUE TITLE
Support Proxy Protocol

### ISSUE THREAD

**Issue by georgeOsdDev** [xitrum-framework/xitrum#613]
I'm using Xitrum behind AWS ELB with tcp listener for wss and https requests.

```
Client - (TCP 443) -> ELB - (TCP 80) -> Xitrums
```

In that case, ELB does not set X-Forwarded-For header because using tcp protocol.
So that I can't get client ip address for access log, etc.

ELB support Proxy Protocol policy.
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html

And netty has HAProxyDecorder
https://github.com/netty/netty/blob/4.1/codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessageDecoder.java

Can we add this handler into xitrum like vert.x
https://github.com/eclipse/vert.x/pull/1271/commits/0da8c05b56609c473da6b53062d5949a92005a54

**Comment by ngocdaothanh** [comment]
I think a config will be added to config/xitrum.conf, to set:
* Whether Proxy Protocol is enabled.
* The version is 1 or 2.

Maybe it will look like this:

```
xitrum {
  ...
  reverseProxy {
    ...
    # http://haproxy.1wt.eu/download/1.5/doc/proxy-protocol.txt
    # http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html
    #proxyProtocol = 1
  }
  ...
}
```

The config is disabled by default.
