### ISSUE TITLE
can give me a demo

### ISSUE THREAD

**Issue by happyer** [xitrum-framework/xitrum#673]
1:can't understand Router<String> router = new Router<String>() .GET("/",             "Index page") 
index page what is  ? 
2:give me demo how to use process http quest and parse param and return response

**Comment by ngocdaothanh** [comment]
There are several demo projects here:
https://github.com/xitrum-framework

For example:

* https://github.com/xitrum-framework/xitrum-demos
* https://github.com/xitrum-framework/xitrum-placeholder

For more detailed instructions, see the Guide Book:
https://xitrum-framework.github.io/guide.html

**Comment by happyer** [comment]
so complex  i wan't simple light httpserver use it

**Comment by caiiiycuk** [comment]
It is not true. I developed a lot with scala for web, and my opinion that xitrum one of the easiest and clean frameworks for scala.

**Comment by ngocdaothanh** [comment]
This framework is for Scala, you must know Scala and SBT to use it.

If you want Java, you can try [WebFlux](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html).
