### ISSUE TITLE
Bump scala 2.13.1

### ISSUE THREAD

**Issue by Ellzord** [xitrum-framework/xitrum#683]
Update scala version to 2.13.1 so we can use latest features.

https://www.scala-lang.org/news/2.13.1
https://www.scala-lang.org/news/2.13.0

**Comment by ngocdaothanh** [comment]
Unfortunately Xitrum is using dependencies that do not support Scala 2.13 yet:
https://github.com/twitter/chill/issues/316

**Comment by ngocdaothanh** [comment]
Memo:
We may have problem with collections when adding Scala 2.13 support:
https://docs.scala-lang.org/overviews/core/collections-migration-213.html

**Comment by Ellzord** [comment]
I will try and keep an eye on these dependencies. It looks like some of them are merged but not yet released.

**Comment by Ellzord** [comment]
https://github.com/twitter/chill/releases/tag/v0.9.5

**Comment by Ellzord** [comment]
@ngocdaothanh is this the only dependency?

**Comment by ngocdaothanh** [comment]
@Ellzord Thanks for the info.

I've just published slf4s-api package for Scala 2.13:
https://github.com/xitrum-framework/slf4s

There's only one more dependency that doesn't support Scala 2.13 yet:
https://github.com/lloydmeta/schwatcher/issues/76

I'll fork and release it for Scala 2.13.

**Comment by ngocdaothanh** [comment]
I'm thinking about replacing Schwatcher (not maintained any more) with better-files (it looks very popular):
https://github.com/pathikrit/better-files#file-monitoring

**Comment by Ellzord** [comment]
Do you need any additional help?

**Comment by AwsomeCui** [comment]
hello，When can support for 2.13 be completed, is the upgrade in progress?

**Comment by ngocdaothanh** [comment]
I've updated Xitrum to add support for Scala 2.13.

In a few hours, I'll update related projects (like xitrum-new and xitrum-demos), and post announcement to the Google forum:
https://groups.google.com/g/xitrum-framework

Stay tuned.

**Comment by ngocdaothanh** [comment]
Xitrum 3.30.0 announcement:
https://groups.google.com/g/xitrum-framework/c/-OpzPcO1-1M
