### ISSUE TITLE
Bump akka to 2.6

### ISSUE THREAD

**Issue by Ellzord** [xitrum-framework/xitrum#684]
Akka has updated to switch to typed actors as default and changed from java serialisation by default.

https://akka.io/blog/news/2019/11/06/akka-2.6.0-released
https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html

It looks like 2.11 will no longer be supported using Akka 2.6.

**Comment by ngocdaothanh** [comment]
Thanks for reporting, I'll bump Akka and release a new version.

**Comment by ngocdaothanh** [comment]
akka-slf4j 2.6.0 doesn't support Scala 2.11:
https://search.maven.org/search?q=akka-slf4j

I'll drop support for Scala 2.11 in Xitrum.

**Comment by ngocdaothanh** [comment]
I've released a new Xitrum version:
https://groups.google.com/forum/#!topic/xitrum-framework/FDNy7_wnrdk

**Comment by Ellzord** [comment]
Great, thanks
